name: 'dbt_bouncer_test_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_bouncer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS dummy_source;"
  - "CREATE TABLE IF NOT EXISTS dummy_source.customers AS SELECT * FROM read_csv('./dbt_project/seeds/raw_customers.csv');"
  - "CREATE SCHEMA IF NOT EXISTS sources_that_dont_really_exist;"
  - "CREATE TABLE IF NOT EXISTS sources_that_dont_really_exist.source_1 AS SELECT * FROM read_csv('./dbt_project/seeds/raw_customers.csv');"
  - "CREATE TABLE IF NOT EXISTS sources_that_dont_really_exist.source_2 AS SELECT * FROM read_csv('./dbt_project/seeds/raw_orders.csv');"
  - "CREATE TABLE IF NOT EXISTS sources_that_dont_really_exist.\"Non_Conforming_Name\" AS SELECT * FROM read_csv('./dbt_project/seeds/raw_payments.csv');"

tests:
  dbt_bouncer_test_project:
    marts:
      +tags:
        - critical

models:
  dbt_bouncer_test_project:
    intermediate:
      +access: protected
      +schema: intermediate
    marts:
      +access: public
      +materialized: table
      +schema: marts
    staging:
      +access: protected
      crm:
        +schema: stg_crm
        +tags:
          - crm
      payments:
        +schema: stg_payments
  internal_package:
    +materialized: table
flags:
  require_generic_test_arguments_property: true
vars:
  fivetran__remove_empty_table_warnings: true
